[package]
name = "detours"
version = "0.1.0"
authors = ["Diana <5275194+DianaNites@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
winapi = "0.3.7"

[build-dependencies]
cc = "1.0.36"
reqwest = "0.9.16"
vswhere = "0.1.0"
bindgen = "0.49.0"
flate2 = "1.0.7"
